export const data1 = [
  {
    id: 15,
    opId: null,
    accType: "A",
    accLeaf: "N",
    accName: "Current Assets",
    parentId: null,
    debit: 0,
    credit: 0,
    children: [
      {
        id: 16,
        opId: null,
        accType: "A",
        accLeaf: "N",
        accName: "Bank Accounts",
        parentId: 15,
        debit: 0,
        credit: 0,
        children: [
          {
            id: 232,
            opId: 761,
            accType: "A",
            accLeaf: "Y",
            accName: "ICICI Bank C/A 400000474",
            parentId: 16,
            debit: 294445,
            credit: 0,
            children: [],
          },
          {
            id: 236,
            opId: null,
            accType: "A",
            accLeaf: "Y",
            accName: "bank5",
            parentId: 16,
            debit: 0,
            credit: 0,
            children: [],
          },
          {
            id: 238,
            opId: null,
            accType: "A",
            accLeaf: "Y",
            accName: "bank7",
            parentId: 16,
            debit: 0,
            credit: 0,
            children: [],
          },
          {
            id: 240,
            opId: null,
            accType: "A",
            accLeaf: "Y",
            accName: "bank9",
            parentId: 16,
            debit: 0,
            credit: 0,
            children: [],
          },
          {
            id: 117,
            opId: 759,
            accType: "A",
            accLeaf: "Y",
            accName: "bank1",
            parentId: 16,
            debit: 378762.02,
            credit: 0,
            children: [],
          },
          {
            id: 242,
            opId: 762,
            accType: "A",
            accLeaf: "Y",
            accName: "bank12",
            parentId: 16,
            debit: 45000,
            credit: 0,
            children: [],
          },
          {
            id: 246,
            opId: null,
            accType: "A",
            accLeaf: "Y",
            accName: "bank15",
            parentId: 16,
            debit: 0,
            credit: 0,
            children: [],
          },
          {
            id: 233,
            opId: 766,
            accType: "A",
            accLeaf: "Y",
            accName: "bank3",
            parentId: 16,
            debit: 5000,
            credit: 0,
            children: [],
          },
          {
            id: 239,
            opId: 758,
            accType: "A",
            accLeaf: "Y",
            accName: "bank8",
            parentId: 16,
            debit: 53100,
            credit: 0,
            children: [],
          },
          {
            id: 241,
            opId: 767,
            accType: "A",
            accLeaf: "Y",
            accName: "bank10",
            parentId: 16,
            debit: 0,
            credit: 2300,
            children: [],
          },
          {
            id: 245,
            opId: null,
            accType: "A",
            accLeaf: "Y",
            accName: "bank14",
            parentId: 16,
            debit: 0,
            credit: 0,
            children: [],
          },
          {
            id: 345,
            opId: 754,
            accType: "A",
            accLeaf: "Y",
            accName: "Kolkata Bank",
            parentId: 16,
            debit: 2100,
            credit: 0,
            children: [],
          },
          {
            id: 331,
            opId: 763,
            accType: "A",
            accLeaf: "Y",
            accName: "ICICI Bank Account 47400074 Goel Food",
            parentId: 16,
            debit: 69000,
            credit: 0,
            children: [],
          },
        ],
      },
      {
        id: 17,
        opId: null,
        accType: "A",
        accLeaf: "N",
        accName: "Cash-in-Hand",
        parentId: 15,
        debit: 0,
        credit: 0,
        children: [
          {
            id: 118,
            opId: 770,
            accType: "A",
            accLeaf: "Y",
            accName: "cash1",
            parentId: 17,
            debit: 60907,
            credit: 0,
            children: [],
          },
        ],
      },
      {
        id: 19,
        opId: null,
        accType: "A",
        accLeaf: "N",
        accName: "Deposits (Asset)",
        parentId: 15,
        debit: 0,
        credit: 0,
        children: [],
      },
    ],
  },
  {
    id: 10,
    opId: null,
    accType: "L",
    accLeaf: "N",
    accName: "Loans Liability",
    parentId: null,
    debit: 0,
    credit: 0,
    children: [
      {
        id: 11,
        opId: null,
        accType: "L",
        accLeaf: "N",
        accName: "Bank OD Account",
        parentId: 10,
        debit: 0,
        credit: 0,
        children: [],
      },
      {
        id: 12,
        opId: null,
        accType: "L",
        accLeaf: "N",
        accName: "Secured Loans",
        parentId: 10,
        debit: 0,
        credit: 0,
        children: [],
      },
    ],
  },
];
