export const DataInstancesMap = {
  accountsEditModal: 'accounts-edit-modal',
  accountsMaster: 'accounts-master',
  accountsOpeningBalance: 'accounts-opening-balance',
  adminBusinessUnits: 'admin-business-units',
  adminBusinessUsers: 'admin-business-users',
  adminDashBoard: 'admin-dashboard',
  adminLinkUsers: 'admin-link-users',
  adminRoles: 'admin-roles',
  adminSecuredControls: 'admin-secured-controls',
  adminSecuredControlsLinkRoles: 'admin-ecured-controls-link-roles',
  allBanks: 'all-banks',
  assets: 'assets',
  balanceSheet: 'balance-sheet',
  bankRecon: 'bank-recon',
  bankReconOpBalance: 'bank-recon-op-balance',
  branchMaster: 'branch-master',
  companyInfo: 'company-info',
  commonUtilsTransferClosingBalance:
    'common-utilities-transfer-closing-balance',
  contactsAndAddresses: 'contacts-and-addresses',
  expenses: 'expenses',
  finYearsMaster: 'fin-years-master',
  generalLedger: 'general-ledger',
  generalSettings: 'general-settings',
  incomes: 'incomes',
  liabilities: 'liabilities',
  newEditBranch: 'new-edit-branch',
  newEditFinYear: 'new-edit-fin-year',
  productCategories: 'product-categories',
  profitLoss: 'profit-loss',
  reportAllTransactions: 'report-all-transactions',
  securedControls: 'secured-controls',
  securedControlsLinkRoles: 'secured-controls-link-roles',
  superAdminAdminUsers: 'super-admin-admin-users',
  superAdminDashBoard: 'super-admin-dashboard',
  superAdminClients: 'super-admin-clients',
  superAdminRoles: 'super-admin-roles',
  superAdminSecuredControls: 'super-addmin-secured-controls',
  trialBalance: 'trial-balance'
}
