export const DataInstancesMap = {
  accountsEditModal: "accounts-edit-modal",
  accountsMaster: "accounts-master",
  adminBusinessUnits: "admin-business-units",
  adminBusinessUsers: "admin-business-users",
  adminDashBoard: "admin-dashboard",
  adminLinkUsers: "admin-link-users",
  adminRoles: "admin-roles",
  adminSecuredControls: "admin-secured-controls",
  adminSecuredControlsLinkRoles: "admin-ecured-controls-link-roles",
  allBanks: "all-banks",
  assets: "assets",
  balanceSheet: "balance-sheet",
  bankRecon: "bank-recon",
  bankReconOpBalance: "bank-recon-op-balance",
  branchMaster:"branch-master",
  companyInfo: "company-info",
  contactsAndAddresses: "contacts-and-addresses",
  editNewBranch:"edit-new-branch",
  expenses: "expenses",
  finYearsMaster:"fin-years-master",
  generalLedger: "general-ledger",
  generalSettings:"general-settings",
  incomes: "incomes",
  liabilities: "liabilities",
  newEditFinYear:"new-edit-fin-year",
  profitLoss: "profit-loss",
  securedControls: "secured-controls",
  securedControlsLinkRoles: "secured-controls-link-roles",
  superAdminAdminUsers: "super-admin-admin-users",
  superAdminDashBoard: "super-admin-dashboard",
  superAdminClients: "super-admin-clients",
  superAdminRoles: "super-admin-roles",
  superAdminSecuredControls: "super-addmin-secured-controls",
  trialBalance: "trial-balance",
};
