export const DataInstancesMap = {
  accountsEditModal: "accounts-edit-modal",
  accountsMaster: "accounts-master",
  accountsOpeningBalance: "accounts-opening-balance",
  adminBusinessUnits: "admin-business-units",
  adminBusinessUsers: "admin-business-users",
  adminDashBoard: "admin-dashboard",
  adminLinkUsers: "admin-link-users",
  adminRoles: "admin-roles",
  adminSecuredControls: "admin-secured-controls",
  adminSecuredControlsLinkRoles: "admin-ecured-controls-link-roles",
  allBanks: "all-banks",
  allTags: "all-tags",
  assets: "assets",
  balanceSheet: "balance-sheet",
  bankRecon: "bank-recon",
  bankReconOpBalance: "bank-recon-op-balance",
  branchMaster: "branch-master",
  brandMaster: "brand-master",
  brandsCategoriesUnits:"brands-categories-units",
  changeCategoryParent: "change-category-parent",
  companyInfo: "company-info",
  commonUtilsTransferClosingBalance:
    "common-utilities-transfer-closing-balance",
  contactsAndAddresses: "contacts-and-addresses",
  expenses: "expenses",
  finYearsMaster: "fin-years-master",
  generalLedger: "general-ledger",
  generalSettings: "general-settings",
  incomes: "incomes",
  // leafCategories:"leaf-categories",
  liabilities: "liabilities",
  manageCategoryHsn: "manage-category-hsn",
  manageTags: "manage-tags",
  newEditBranch: "new-edit-branch",
  newEditFinYear: "new-edit-fin-year",
  newEditTag: "new-edit-tag",
  productCategories: "product-categories",
  productMaster: "product-master",
  productOnId:"product-on-id",
  productsOpeningBalances:"products-opening-balances",
  profitLoss: "profit-loss",
  reportAllTransactions: "report-all-transactions",
  securedControls: "secured-controls",
  securedControlsLinkRoles: "secured-controls-link-roles",
  superAdminAdminUsers: "super-admin-admin-users",
  superAdminDashBoard: "super-admin-dashboard",
  superAdminClients: "super-admin-clients",
  superAdminRoles: "super-admin-roles",
  superAdminSecuredControls: "super-addmin-secured-controls",
  trialBalance: "trial-balance",
};
