export const SqlIdsMap = {
  //Security
  allAdminRoles: "get_all_admin_roles_onClientId",
  allAdminUsers: "get_all_admin_users",
  allBusinessUsers: "get_all_business_users_on_clientId",
  allBusinessUnits: "get_all_business_units_on_clientId",
  adminDashBoard: "get_admin_dashboard",
  allClients: "get_all_clients",
  allRoles: "get_all_roles",
  allSecuredControls: "get_all_secured_controls",
  deleteBusinessUnit:"delete_business_unit",
  getAdminRoleOnRoleNameClientId: "get_admin_role_on_roleName_clientId",
  getAdminRolesSecuredControlsLink: "get_admin_roles_securedControls_link",
  getAllClientNamesNoArgs: "get_all_client_names_no_args",
  getAllRoleNamesOnClientIdWithBuiltinRoles:
    "get_all_role_names_on_clientId_with_builtin_roles",
  getBuiltinRoles: "get_builtin_roles",
  getBuOnBuCodeAndClientId: "get_bu_on_buCode_and_clientId",
  getBuUsersLink: "get_bu_users_link",
  getClientOnClientCode: "get_client_on_clientCode",
  getClientOnClientName: "get_client_on_clientName",
  getRolesSecuredControlsLink: "get_roles_securedControls_link",
  getSecuredControlsNotLinkedWithRoleId:
    "get_securedControls_not_linked_with_roleId",
  getSuperAdminRoleOnRoleName: "get_super_admin_role_on_role_name",
  getSuperAdminControlOnControlName: "get_super_admin_control_on_control_name",
  getUserIdOnClientIdEmail: "get_userId_on_clientId_and_email",
  getUserIdOnClientIdUid: "get_userId_on_clientId_and_uid",
  getUsersNotLinkedWithBuIdExcludeAdmin:
    "get_users_not_linked_with_buId_exclude_admin",
  insertSecuredControlsFromBuiltinRole:
    "insert_securedControls_from_builtin_role",
  superAdminDashBoard: "get_super_admin_dashboard",
  testConnection: "test_connection",

  // accounts
  doesAccCodeExist: "does_acc_code_exist",
  doesAccNameExist: "does_acc_name_exist",
  doesCatIdBrandIdProductLabelExist: "does_catId_brandId_product_label_exist",
  doesOtherCatIdBrandIdProductLabelExist:
    "does_other_catId_brandId_product_label_exist",
  doesCatNameExist: "does_category_name_exist",
  doesOtherCatNameExist: "does_other_category_name_exist",
  doesOtherTagNameExist: "does_other_tag_name_exist",
  doesTagNameExist: "does_tag_name_exist",
  executeStockTransfer: "execute_stock_transfer",
  getAccountBalance: "get_account_balance",
  getAccountsOpeningBalance: "get_accounts_opening_balance",
  getAccountLedger: "get_account_ledger",
  getAccountParentOptions: "get_account_parent_options",
  getAllBanks: "get_all_banks",
  getAllBranches: "get_all_branches",
  getAllBranchTransferHeaders: "get_all_branch_transfer_headers",
  getAllBrands: "get_all_brands",
  getAllSchemasInDatabase: "get_all_schemas_in_database",
  getAllTransactions: "get_all_transactions",
  getBankOpBalance: "get_bank_op_balance",
  getBranchTransferDetailsOnTranHeaderId:
    "get_branch_transfer_details_on_tran_header_id",
  getBrandsOnCatId: "get_brands_on_catId",
  getAllProducts: "get_all_products",
  getAllProductsInfoForProductSelect:
    "get_all_products_info_for_product_select",
  getAllStockJournals: "get_all_stock_journals",
  getBankRecon: "get_bank_recon",
  getBrandsCategoriesTags: "get_brands_categories_tags",
  getBrandsCategoriesUnits: "get_brands_categories_units",
  getCurrentOrders: "get_current_orders",
  getExtBusinessContactsAccM: "get_extBusinessContactsAccM",
  getFinYears: "get_fin_years",
  getLeafCategories: "get_leaf_categories",
  getLeafCategoriesWithParent: "get_leaf_categories_with_parent",
  getLedgerLeafAccounts: "get_ledger_leaf_accounts",
  getLedgerLeafSubLedgerAccounts: 'get_ledger_leaf_subledger_accounts',
  getProductLabelsOnCatIdBrandId: "get_product_labels_on_catId_brandId",
  getProductOnId: "get_product_on_id",
  getProductOnProductCodeUpc: "get_product_on_product_code_upc",
  getProductsOpeningBalances: "get_products_opening_balances",
  getPurchasePriceVariation: "get_purchase_price_variation",
  getPurchaseReport: "get_purchase_report",
  getSalesReport: "get_sales_report",
  getSettingsFinYearsBranches: "get_settings_fin_years_branches",
  getStockJournalOnTranHeaderId: "get_stock_journal_on_tran_header_id",
  getStockSummaryReport: "get_stock_summary_report",
  getStockTransReport: "get_stock_trans_report",
  getSubledgerAccounts: "get_subledger_accounts",
  getTags: "get_tags",
  getTrialBalance: "get_trial_balance",
  insertProduct: "insert_product",
  updateAccountsMaster: "update_accounts_master",
  upsertAutoSubledger: "upsert_auto_subledger",
  upsertGeneralSettings: "upsert_general_settings",
  upsertProductOpeningBalance: "upsert_product_opening_balance",
  upsertTransferClosingBalance: "upsert_transfer_closing_balance",
  upsertUnitInfo: "upsert_unit_info",
};
