export const DataInstancesMap = {
  accountsEditModal: "accounts-edit-modal",
  accountsMaster: "accounts-master",
  accountsOpeningBalance: "accounts-opening-balance",
  adminBusinessUnits: "admin-business-units",
  adminBusinessUsers: "admin-business-users",
  adminDashBoard: "admin-dashboard",
  adminLinkUsers: "admin-link-users",
  adminRoles: "admin-roles",
  adminSecuredControls: "admin-secured-controls",
  adminSecuredControlsLinkRoles: "admin-ecured-controls-link-roles",
  allBanks: "all-banks",
  allTags: "all-tags",
  allVouchers:'all-vouchers',
  assets: "assets",
  balanceSheet: "balance-sheet",
  bankRecon: "bank-recon",
  bankReconOpBalance: "bank-recon-op-balance",
  branchMaster: "branch-master",
  brandMaster: "brand-master",
  brandsCategoriesUnits: "brands-categories-units",
  brandsOnCatId: "brands-on-cat-id",
  changeCategoryParent: "change-category-parent",
  companyInfo: "company-info",
  commonUtilsTransferClosingBalance:
    "common-utilities-transfer-closing-balance",
  contactsAndAddresses: "contacts-and-addresses",
  currentOrdersReport: "current-orders-report",
  expenses: "expenses",
  finYearMaster: "fin-year-master",
  generalLedger: "general-ledger",
  generalSettings: "general-settings",
  incomes: "incomes",
  // leafCategories:"leaf-categories",
  leafCategoriesWithParent: "leaf-categories-with-parent",
  liabilities: "liabilities",
  manageCategoryHsn: "manage-category-hsn",
  manageTags: "manage-tags",
  newEditBranch: "new-edit-branch",
  newEditFinYear: "new-edit-fin-year",
  newEditTag: "new-edit-tag",
  productCategories: "product-categories",
  productMaster: "product-master",
  productOnId: "product-on-id",
  productLabelsOnCatIdBrandId: "product-labels-on-cat-id-brand-id",
  productsBranchTransfer: "products-branch-transfer",
  productsOpeningBalances: "products-opening-balances",
  productSelect: "product-select",
  productsListReport: "products-list-report",
  profitLoss: "profit-loss",
  purchasePriceVariationReport:"purchase-price-variation-report",
  purchaseReport:"purchase-report",
  reportAllTransactions: "report-all-transactions",
  salesReport: "sales-report",
  securedControls: "secured-controls",
  securedControlsLinkRoles: "secured-controls-link-roles",
  stockJournal: "stock-journal",
  stockSummaryReport: "stock-summary-report",
  stockTransReport:"stock-trans-report",
  superAdminAdminUsers: "super-admin-admin-users",
  superAdminDashBoard: "super-admin-dashboard",
  superAdminClients: "super-admin-clients",
  superAdminRoles: "super-admin-roles",
  superAdminSecuredControls: "super-addmin-secured-controls",
  trialBalance: "trial-balance",
};
